### ISSUE TITLE
fix osx x86_64 build

### ISSUE THREAD

**Issue by ltalirz** [conda-forge/zeopp-lsmo-feedstock#14]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

PR #6 unpinned the version of the Eigen library

Since then, one of the tests fails on OSX

### Installed packages

```shell
...
```

### Environment info

```shell
...
```

**Comment by kjappelbaum** [comment]
let's continue to track this in https://github.com/lsmo-epfl/zeopp-lsmo, as it is not really an issue with the conda recipe
